baseURL = 'https://SewiR3.github.io/engineering-log/'
title = 'Engineering Log'
theme = 'anatole'
locale = 'en-us'

[privacy]
  disallow = ["twitter", "youtube", "vimeo", "instagram", "disqus", "googleanalytics"]